#!/usr/bin/env bash
# Command line to install nginx
sudo apt-get -y update
sudo apt-get -y install nginx
chmod u+x /var/www/html/index.nginx-debian.html
sudo chown -R "$USER":"$USER" /var/www/html/index.nginx-debian.html
sudo chmod -R 755 /var/www/
sudo echo "Hello World" > /var/www/html/index.nginx-debian.html
sudo service nginx start
