#!/usr/bin/env bash
#run 
pkill apache2
chown -R nginx:nginx /ect/nginx/nginx.conf
chmod +x /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-available/default
sudo -u nginx service nginx reload
sudo -u nginx service nginx start
